name: gdziemojhajsapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^1.1.0
  flutter_statusbarcolor: ^0.2.3
  json_serializable: ^3.3.0
  equatable: ^1.1.1
  json_annotation: ^3.0.0
  flushbar: 1.10.0
  http: ^0.12.0+4
  fab_circular_menu: ^1.0.0
  pie_chart: ^3.1.1
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  unicorndial: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  image_test_utils: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/jedzenie.jpg
    - images/sprzet.jpg
    - images/transport.jpg
    - images/relaks.jpg
    - images/mieszkanie.jpg
    - images/higiena.jpg
    - images/odziez.jpg
    - images/rachunki.jpg